pipeline{
    agent any
    stages{
        stage("Clone"){
            steps{
                dir('terraform'){
                bat 'terraform init'
                bat 'terraform plan'
                }
            }
        }
    }
  
}
