pipeline{
    agent any
    stages{
        stage("Clone"){
            steps{
                dir('terraform'){
                    withAWS(credentials: 'aws_creds', region: 'us-east-1') {
                        bat 'terraform init'
                        bat 'terraform plan -var-file=spruce.tfvars'
                    }
                }
            }
        }
    }
  
}
